### ISSUE TITLE
WorldToScreen transformation is not correct

### ISSUE THREAD

**Issue by tienpp** [guided-hacking/Age_of_Empires_II_Definitive-Edition#3] opened 2020-04-28 14:14 UTC
Hi,

The WorldToScreen transformation is not working correctly. The boxes for resources any other units are not pointing to exact their location, but moving along.

I'm testing in full screen mode, video for reference: https://streamable.com/davs91

**Comment by BDKPlayer** [comment] 2020-04-30 10:49
Thanks for reporting this problem. I do have some questions so I can reproduce the problem:

1. What resolution are you using?
2. What display mode (fullscreen, window..)?
3. Are you using the "enhanced graphics pack"?

**Comment by tienpp** [comment] 2020-05-01 00:39
Hi,
1. resolution 2880x1620
2. Fullscreen 
3. No
![image](https://user-images.githubusercontent.com/2742099/80771835-a1d69400-8b8f-11ea-9cbc-ffc989e97dd4.png)

Thanks

**Comment by BDKPlayer** [comment] 2020-05-01 08:50
First time I see this resolution tbh. Is that a 3k monitor?

 Can you try running the game in any 16:9 aspect ratio like?

720p
1080p
1440p

I took me a while to get the ESP right and I couldnt have it done without try and error. I mean take a look at the worldToScreen code. Maybe you can adapt it to work on your resolution.

**Comment by BDKPlayer** [comment] 2020-05-03 12:13
closed as I cant reproduce the error to fix it and I currently have no interest in trying to support "unusual" resolutions. If you or anybody reading this wants to provide a fix that doesn't break other resolution please create a pull request and Im more than happy to merge it :)

**Closed by BDKPlayer** 2020-05-03 12:13 UTC
